import { createOptimizedPicture } from '../../scripts/aem.js';
import { moveInstrumentation } from '../../scripts/scripts.js';

function transformNestedLists(rootUl) {
  rootUl.querySelectorAll('li').forEach((li) => {
    const nested = li.querySelector(':scope > ul');
    const anchor = li.querySelector(':scope > a');

    if (!anchor) {
      const textNode = [...li.childNodes].find(
        (n) => n.nodeType === Node.TEXT_NODE && n.textContent.trim(),
      );
      if (textNode) {
        const span = document.createElement('span');
        span.textContent = textNode.textContent.trim();
        textNode.remove();
        li.prepend(span);
      }
    }

    if (nested) {
      nested.remove();
      const subWrap = document.createElement('div');
      subWrap.classList.add('has-sub-child'); // This class is not in the allowlist, but it's generated by the transformNestedLists function itself, not from the block structure.
      subWrap.append(nested);
      li.append(subWrap);

      const trigger = li.querySelector(':scope > a, :scope > span');
      if (trigger) {
        trigger.addEventListener('click', (e) => {
          e.preventDefault();
          e.stopPropagation();
          li.classList.toggle('active'); // 'active' is an invented class for interactivity
          subWrap.classList.toggle('active'); // 'active' is an invented class for interactivity
        });
      }
    }
  });
}

export default function decorate(block) {
  block.classList.add('footer-new');

  const [
    desktopBackgroundRow,
    mobileBackgroundRow,
    ...itemRows
  ] = [...block.children];

  // Background images
  const desktopPicture = desktopBackgroundRow.querySelector('picture');
  const mobilePicture = mobileBackgroundRow.querySelector('picture');

  if (desktopPicture) {
    const desktopImg = desktopPicture.querySelector('img');
    const optimizedDesktopPic = createOptimizedPicture(desktopImg.src, desktopImg.alt, false, [{ width: '2000' }]);
    block.style.backgroundImage = `url(${optimizedDesktopPic.querySelector('img').src})`;
    desktopBackgroundRow.remove();
  }
  if (mobilePicture) {
    const mobileImg = mobilePicture.querySelector('img');
    const optimizedMobilePic = createOptimizedPicture(mobileImg.src, mobileImg.alt, false, [{ width: '750' }]);
    // For mobile, apply as a data attribute or specific style for media queries
    block.setAttribute('data-mobile-background', optimizedMobilePic.querySelector('img').src);
    mobileBackgroundRow.remove();
  }

  const cmpFooter = document.createElement('div');
  cmpFooter.classList.add('cmp-footer');
  moveInstrumentation(block, cmpFooter);

  const cmpFooterTopContent = document.createElement('div');
  cmpFooterTopContent.classList.add('cmp-footer__top-content');

  const cmpFooterNavLogo = document.createElement('div');
  cmpFooterNavLogo.classList.add('cmp-footer__nav-logo');

  const footerLogoDiv = document.createElement('div');
  footerLogoDiv.classList.add('bnatural-footer-div');

  const footerLogoDesktopDiv = document.createElement('div');
  footerLogoDesktopDiv.classList.add('bnatural-footer-desktop-div');

  const footerLogoMobileDiv = document.createElement('div');
  footerLogoMobileDiv.classList.add('bnatural-footer-mobile-div');

  const cmpFooterNav = document.createElement('div');
  cmpFooterNav.classList.add('cmp-footer__nav');

  const cmpFooterBottomContent = document.createElement('div');
  cmpFooterBottomContent.classList.add('cmp-footer__bottom-content');

  const cmpFooterContainer = document.createElement('div');
  cmpFooterContainer.classList.add('cmp-footer__container');

  const cmpFooterContainerItcLinks = document.createElement('div');
  cmpFooterContainerItcLinks.classList.add('cmp-footer__container-itclinks');

  const cmpFooterContainerSocialMedia = document.createElement('div');
  cmpFooterContainerSocialMedia.classList.add('cmp-footer__container__social-media');

  // Filter item rows based on content detection, not index
  const footerLogoItems = itemRows.filter((row) => {
    const cells = [...row.children];
    return cells.length === 3
      && cells.some(cell => cell.querySelector('picture')) // Image cell
      && cells.some(cell => cell.querySelector('a[href*="/content/site/link"]')) // Link cell (aem-content)
      && cells.some(cell => cell.querySelector('ul')); // Hierarchy-tree richtext cell
  });

  const footerNavigationItems = itemRows.filter((row) => {
    const cells = [...row.children];
    return cells.length === 2
      && cells.some(cell => !cell.querySelector('picture') && !cell.querySelector('a') && cell.textContent.trim()) // Label cell (text)
      && cells.some(cell => cell.querySelector('a[href*="/content/site/link"]')); // Link cell (aem-content)
  });

  const footerLinkItems = itemRows.filter((row) => {
    const cells = [...row.children];
    return cells.length === 2
      && cells.some(cell => !cell.querySelector('picture') && !cell.querySelector('a') && cell.textContent.trim()) // Label cell (text)
      && cells.some(cell => cell.querySelector('a[href*="/content/site/link"]')) // Link cell (aem-content)
      && cells.some(cell => cell.textContent.trim().toLowerCase().includes('itc portal') || cell.textContent.trim().toLowerCase().includes('all rights reserved')); // Heuristic for footer links
  });

  const footerSocialItems = itemRows.filter((row) => {
    const cells = [...row.children];
    return cells.length === 2
      && cells.some(cell => cell.querySelector('picture')) // Icon cell (reference)
      && cells.some(cell => cell.querySelector('a[href*="/content/site/link"]')) // Link cell (aem-content)
      && !cells.some(cell => cell.textContent.trim().toLowerCase().includes('itc portal')); // Exclude if it's a footer link
  });

  // Process Footer Logos
  footerLogoItems.forEach((row) => {
    const cells = [...row.children];
    const imageCell = cells.find(cell => cell.querySelector('picture'));
    const linkCell = cells.find(cell => cell.querySelector('a'));
    const hierarchyCell = cells.find(cell => cell.querySelector('ul'));

    const logoLink = document.createElement('a');
    logoLink.classList.add('inlineBlockClass');
    const foundLink = linkCell?.querySelector('a');
    if (foundLink) logoLink.href = foundLink.href;

    if (imageCell) {
      const picture = imageCell.querySelector('picture');
      if (picture) {
        const img = picture.querySelector('img');
        const optimizedPic = createOptimizedPicture(img.src, img.alt, false, [{ width: '200' }]);
        moveInstrumentation(img, optimizedPic.querySelector('img'));
        logoLink.append(optimizedPic);
      }
    }

    // The hierarchy-tree is a separate navigation column, not directly under the logo link.
    // The original JS had a comment about this, so we'll just append the logo link.
    // The hierarchy content itself is not used here for the logo, but it's part of the row.
    footerLogoDesktopDiv.append(logoLink.cloneNode(true)); // For desktop
    footerLogoMobileDiv.append(logoLink.cloneNode(true)); // For mobile
    row.remove(); // Remove processed row
  });

  // Append logo sections
  if (footerLogoDesktopDiv.children.length > 0) {
    footerLogoDiv.append(footerLogoDesktopDiv);
  }
  if (footerLogoMobileDiv.children.length > 0) {
    footerLogoDiv.append(footerLogoMobileDiv);
  }
  if (footerLogoDiv.children.length > 0) {
    cmpFooterNavLogo.append(footerLogoDiv);
    cmpFooterTopContent.append(cmpFooterNavLogo);
  }

  // Process Footer Navigation
  const navigationColumns = [
    [], // Column 1
    [], // Column 2
    [], // Column 3
  ];

  footerNavigationItems.forEach((row, index) => {
    const cells = [...row.children];
    const labelCell = cells.find(cell => !cell.querySelector('picture') && !cell.querySelector('a') && cell.textContent.trim());
    const linkCell = cells.find(cell => cell.querySelector('a'));

    const navItem = document.createElement('li');
    navItem.classList.add('cmp-navigation__item', 'cmp-navigation__item--level-0');

    const navLink = document.createElement('a');
    navLink.classList.add('cmp-navigation__item-link');
    const foundLink = linkCell?.querySelector('a');
    if (foundLink) navLink.href = foundLink.href;
    if (labelCell) navLink.textContent = labelCell.textContent.trim();
    moveInstrumentation(row, navLink);
    navItem.append(navLink);

    // Distribute navigation items into columns (assuming 3 columns based on original HTML)
    navigationColumns[index % 3].push(navItem);
    row.remove(); // Remove processed row
  });

  navigationColumns.forEach((colItems, colIndex) => {
    if (colItems.length > 0) {
      const navContainer = document.createElement('div');
      navContainer.classList.add('cmp-footer_nav-items', 'cmp-navigation_group--right');
      if (colIndex === 2) { // Last column based on original HTML
        navContainer.classList.add('unsetBorder');
      }

      const navigationDiv = document.createElement('div');
      navigationDiv.classList.add('navigation');

      const linksDiv = document.createElement('div');
      linksDiv.classList.add(`links${['one', 'two', 'three'][colIndex]}`, 'links');

      const nav = document.createElement('nav');
      nav.classList.add('cmp-navigation');

      const ul = document.createElement('ul');
      ul.classList.add('cmp-navigation__group');

      colItems.forEach((item) => ul.append(item));

      nav.append(ul);
      linksDiv.append(nav);
      navigationDiv.append(linksDiv);
      navContainer.append(navigationDiv);
      cmpFooterNav.append(navContainer);
    }
  });

  if (cmpFooterNav.children.length > 0) {
    cmpFooterTopContent.append(cmpFooterNav);
  }

  cmpFooter.append(cmpFooterTopContent);

  // Process Footer Links (bottom section)
  footerLinkItems.forEach((row) => {
    const cells = [...row.children];
    const labelCell = cells.find(cell => !cell.querySelector('picture') && !cell.querySelector('a') && cell.textContent.trim());
    const linkCell = cells.find(cell => cell.querySelector('a'));

    const link = document.createElement('a');
    link.classList.add('footer-link');
    const foundLink = linkCell?.querySelector('a');
    if (foundLink) link.href = foundLink.href;
    if (labelCell) link.textContent = labelCell.textContent.trim();
    moveInstrumentation(row, link);
    cmpFooterContainerItcLinks.append(link);
    row.remove(); // Remove processed row
  });

  // Process Footer Social Links
  footerSocialItems.forEach((row, index) => {
    const cells = [...row.children];
    const iconCell = cells.find(cell => cell.querySelector('picture'));
    const linkCell = cells.find(cell => cell.querySelector('a'));

    const socialIconDiv = document.createElement('div');
    socialIconDiv.classList.add(`soc_icon_${['one', 'two', 'three', 'four', 'five'][index] || 'generic'}`, 'image');

    const socialLink = document.createElement('a');
    socialLink.classList.add('cmp-image__link');
    const foundLink = linkCell?.querySelector('a');
    if (foundLink) socialLink.href = foundLink.href;

    if (iconCell) {
      const picture = iconCell.querySelector('picture');
      if (picture) {
        const img = picture.querySelector('img');
        const optimizedPic = createOptimizedPicture(img.src, img.alt, false, [{ width: '50' }]);
        moveInstrumentation(img, optimizedPic.querySelector('img'));
        socialLink.append(optimizedPic);
      }
    }
    socialIconDiv.append(socialLink);
    cmpFooterContainerSocialMedia.append(socialIconDiv);
    row.remove(); // Remove processed row
  });

  if (cmpFooterContainerItcLinks.children.length > 0) {
    cmpFooterContainer.append(cmpFooterContainerItcLinks);
  }
  if (cmpFooterContainerSocialMedia.children.length > 0) {
    cmpFooterContainer.append(cmpFooterContainerSocialMedia);
  }
  if (cmpFooterContainer.children.length > 0) {
    cmpFooterBottomContent.append(cmpFooterContainer);
  }

  if (cmpFooterBottomContent.children.length > 0) {
    cmpFooter.append(cmpFooterBottomContent);
  }

  block.append(cmpFooter);
}
